jdk: oraclejdk8
language: android
android:
  components:
    - tools
    - platform-tools #
    - tools # Bug with Travis - ensure BT 25 is installed (https://github.com/travis-ci/docs-travis-ci-com/issues/779)
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - ./gradlew build test
after_failure:
  - cat /home/travis/build/longdivision/hex/app/build/outputs/lint-results.html
